### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by zsg555** [nihui/ncnn-android-yolov5#40]
运行demo时报错： No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
使用的ndk版本为25.0.8775105
![image](https://user-images.githubusercontent.com/5673993/180636758-6f49bfa0-14f8-4ca5-9b5b-0d1583807a73.png)

帮忙看下怎么解决

**Comment by zsg555** [comment]
已解决，换了NDK21版本就可以了

**Comment by yangsuhui** [comment]
@zsg555 你好，请问你具体用的是NDK21.1.几啊？我也遇到这个问题，同时你有遇到libyolov5ncnn.so找不到得错误吗？

**Comment by zsg555** [comment]
版本是 21.4.7075529
