### ISSUE TITLE
注册自定义层，使用ncnn2mem转化成*.h文件加载还是会报layer -1 not exists or registered

### ISSUE THREAD

**Issue by DingYiWen** [nihui/ncnn-android-yolov5#5]
大佬你好，按照你写的步骤我都能成功，但是这个只能加载*.param 和*.bin文件，如果用ncnn2mem转化成*.h文件加载还是会报layer -1 not exists or registered的问题，请问您知道怎么解决吗？

**Comment by nihui** [comment]
最新的ncnn已经支持了
